services:

  auth-service:
    build: services/auth-service
    container_name: payshield-auth
    ports:
      - "8002:8080"
    env_file: .env
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      REDIS_URL: redis://redis:6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      dynamodb-local:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - payshield-network
    restart: unless-stopped

  backend-bff:
    build: services/backend-bff
    container_name: payshield-bff
    ports:
      - "8001:8080"
    env_file: .env
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      TRANSACTION_SERVICE_URL: http://transaction-service:8080
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      - payshield-network
    restart: unless-stopped

  transaction-service:
    build:
      context: services/transaction-service
      dockerfile: Dockerfile
    container_name: payshield-transaction
    ports:
      - "8003:8080"
    env_file: .env
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FRAUD_MODEL_API_URL: http://fraud-model-api:8080
      APP_ENV: development
    depends_on:
      dynamodb-local:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - payshield-network
    restart: unless-stopped

  feature-service:
    build:
      context: services/feature-service
      dockerfile: Dockerfile
    container_name: payshield-feature
    ports:
      - "8005:8080"
    env_file: .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_URL: redis://redis:6379
      FRAUD_MODEL_API_URL: http://fraud-model-api:8080
      TRANSACTION_SERVICE_URL: http://transaction-service:8080
      APP_ENV: development
    depends_on:
      - kafka
      - redis
      - transaction-service
    networks:
      - payshield-network
    restart: unless-stopped
